### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by MirkoDziadzka** [looking-for-a-job/applescript.py#1]
I'm writing a library which execute a lot of small apple scripts, possible some 1000 in a single run.

I run into the exception

```
File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1441, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
```

I checked the library code and it looks that it opens a new temporary file for every single apple script execution and never close the file descriptor. Which after some 100 calls, results in this OS error.

Finally I used a different approach which did not use a temporary file but pipes the script via stdin to the `osascript`

It runs basically around the lines

```py
proc = subprocess.Popen(["osascript", "-"],
                                stdin=subprocess.PIPE,
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE)
out, err = proc.communicate(input=cmd.encode("utf-8"))
status = proc.returncode
```

**Comment by andrewpetrochenkov** [comment]
fixed. thx
