### ISSUE TITLE
applescript.run() defaults to javascript=True

### ISSUE THREAD

**Issue by pklaus** [looking-for-a-job/applescript.py#4]
Thanks for the lib! While trying it out, I cam across a bug / undocumented change introduced by 67948c7:

The replace [line 13](https://github.com/andrewp-as-is/applescript.py/commit/67948c71bdba9dbdd2987fc969e0f170c493d5bf#diff-59725eef8fe7691f0731b420c5ca2513378ce6c2622c057ec89775052777bfbcR13) of `applescript/__init__.py` changes the default to the execution of Javascript:
```diff
-def run(applescript, background=False):
+def run(applescript, background=False, javascript=True):
```

This was unexpected / confusing for me and is not consistent with the examples stated in the README:

```python
>>> import applescript
>>> r = applescript.run('return 1')
>>> r.code, r.out, r.err
(1, '', '0:8: syntax error: Error on line 1: SyntaxError: Return statements are only valid inside functions. (-2700)')
```

Without `javascript` set to `False` it works as expected:
```python
>>> r = applescript.run('return 1', javascript=False)
>>> r.code, r.out, r.err
(0, '1', '')
```

**Comment by andrewpetrochenkov** [comment]
thx, fixed
