### ISSUE TITLE
Can i use this lib to run bash/shell script files in terminal?

### ISSUE THREAD

**Issue by pssolanki111** [looking-for-a-job/applescript.py#5]
hi there,
Thanks for the excellent lib :)

I have a use case. I have a bash script (stored in the same directory as my python script) and I need to run that so it opens a terminal and runs the file. Similar with the shell script. The shell script does have some `sudo` commands and I think the user would need to enter their sudo pwd hence I need the terminal opened up as well.

I was wondering if that's possible using something like `applescript.tell.app('Terminal', 'fileName.sh')` or similar stuff?

Any help is greatly appreciated :)

**Comment by andrewpetrochenkov** [comment]
1) fileName.sh
```
#!/usr/bin/open -a Terminal

YOUR CODE
```

2)
```
osascript <<EOF
tell application "Terminal"
    do script with command "bash /path/to/fileName.sh"
    activate
end tell
EOF
```

**Comment by pssolanki111** [comment]
Hey Andrew, Appreciate the response : )

Sorry for being dense but how do I implement this in the module?

do I have to do 

```py
applescript.run('''osascript <<EOF
    tell application "Terminal"
        do script with command "bash /path/to/fileName.sh"
        activate
    end tell
    EOF''')
```

**Comment by andrewpetrochenkov** [comment]
don't use my trash module :) 

```
#!/usr/bin/env python
import subprocess

applescript="""
tell application "Terminal"
    do script with command "bash /path/to/filename.sh"
    activate
end tell
"""
subprocess.run(["/usr/bin/osascript"],input=applescript.encode())  # doesn't capture output
```

[subprocess — Subprocess management](https://docs.python.org/3/library/subprocess.html)

**Comment by pssolanki111** [comment]
`applescript` is a good utility lib in all honesty. It may not be suitable for my use case but it certainly is very helpful when working with pure apple script. I'm not saying this to sound modest or be nice but I mean it : ) any contribution made towards the open source community is priceless and you've done that so kudos to you : )

I'm assuming for a shell script (not a bash script), I'll change `"bash fileName.sh"` to `"sh fileName.sh"` - or maybe `"/usr/bin/sh fileName.sh"`, right?

also what change do I make to capture the output, not the entire thing but maybe just the status of whether the things went through or not?

maybe using `stdout=subprocess.PIPE` or something? 

I was honestly trying to avoid using `subprocess` or `os.system` calls but you've given me hope :D

**Comment by pssolanki111** [comment]
I figured out how to capture output from the docs, gotta use `capture_output=True, text=True` in the `subprocess.run()` call. 

I'm still not sure about running shell vs bash using code above, but I'll prolly figure that out.

Appreciate the help, I really do : )
